language: node_js
node_js: '10.12'
# every second counts
git:
  depth: 5
env:
  global:
    - NODE_ENV=production
    # We may want to run eslint as a separate step in the CI process for improved performance and error reporting when there are eslint issues.
    - DISABLE_AUTOMATIC_ESLINT=true
jobs:
  include:
    - stage: test
      name: "Check if a changelog entry exists"
      if: type = pull_request
      install: true # skip install since it has no dependencies
      script:
        - node scripts/require-changelog-entry.js
    - stage: test
      name: "code-quality: eslint"
      cache:
        directories:
          - $HOME/.npm
      install:
        - npm ci --dev
      script:
        - npm run lint -- --max-warnings=0
    - stage: test
      name: "tests"
      cache:
        directories:
          - $HOME/.npm
      install:
        - npm ci --dev
      script:
        - npm run test -- --maxWorkers=2
    - stage: build
      language: generic
      services: docker
      script: docker build --tag wowanalyzer --build-arg REACT_APP_ENVIRONMENT_NAME=$TRAVIS_BRANCH --build-arg REACT_APP_VERSION=$TRAVIS_COMMIT --build-arg DISABLE_AUTOMATIC_ESLINT=true .
      # Reminder: deploy doesn't run on PRs
      deploy:
        provider: script
        skip_cleanup: true
        script: bash .travis/deploy.sh
        on:
          all_branches: true
after_failure:
  - chmod +x .travis/discord-hook/fail.sh
  - ./.travis/discord-hook/fail.sh
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
